# Generated by Django 4.2.7 on 2023-11-26 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.IntegerField()),
                ('apellidos', models.TextField()),
                ('nombres', models.TextField()),
                ('email_agente', models.TextField()),
                ('jefe_directo', models.TextField()),
                ('email_jefe_directo', models.TextField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.SmallIntegerField(default=0)),
                ('anio', models.SmallIntegerField(default=0)),
                ('presentado', models.BooleanField(default=False)),
                ('agente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='partes.agentes')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.SmallIntegerField()),
                ('codigo', models.CharField(max_length=3)),
                ('observaciones', models.TextField()),
                ('planilla', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='partes.planilla')),
            ],
        ),
    ]
