# Generated by Django 4.2.7 on 2023-11-29 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegeneracionPW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=64)),
                ('agente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='partes.agentes')),
            ],
        ),
    ]
