# Generated by Django 4.2.7 on 2023-12-04 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0003_empleado_puesto_statusplanilla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='jefe_directo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='partes.empleado'),
        ),
    ]
