# Generated by Django 4.2.7 on 2024-01-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0004_alter_empleado_jefe_directo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='observaciones',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='observaciones',
            field=models.TextField(default=''),
        ),
    ]
