# Generated by Django 4.2.7 on 2024-02-08 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0005_planilla_observaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('description', models.TextField()),
                ('empleado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='partes.empleado')),
            ],
        ),
    ]
