# Generated by Django 4.2.7 on 2024-05-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0008_remove_planilla_pdf_adjunto_adjuntos'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechasLimites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.SmallIntegerField(default=0)),
                ('anio', models.SmallIntegerField(default=0)),
                ('diaLimite', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
